name: RSpec
on:
  pull_request:
  push:
  schedule:
    - cron: '11 21 * * *'
jobs:
  RSpec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: amancevice/setup-code-climate@v0
      with:
        cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
    - run: cc-test-reporter before-build
    - run: gem install bundler
    - run: bundle install --jobs 4 --retry 3
    - run: bundle exec rake
    - run: cc-test-reporter after-build
      if: ${{ github.event_name != 'pull_request' }}
